name: CI

on:
  # Trigger the workflow manually using the Actions tab on GitHub, GitHub CLI, or the REST API
  workflow_dispatch:
  # Trigger the workflow on Push event to main branch
  push:
    branches: [ main ]
  # Trigger the workflow on Pull Request event. By default, a workflow only runs
  # when a Pull Request event's activity type is opened, synchronize or reopened.
  pull_request:
    types: [ opened, synchronize, reopened ]

# Cancel any current or previous job from the same Pull Request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  local-tests:
    name: Check Local Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - name: Run local tests (JVM)
        run: ./gradlew testDebug --no-daemon

      - name: Upload local tests reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: local-tests-reports
          path: ./**/build/reports/tests/

  android-tests:
    name: Check Android Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - name: Run android tests (real device or emulator)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86
          profile: Nexus 6
          disable-animations: true
          script: ./gradlew connectedCheck

      - name: Upload android tests reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-tests-reports
          path: ./**/build/reports/ui-tests/
